defaults:
  - optimizer: sgd
  - schedulers: cosine_annealing_with_warmup

data:
  train:
    data_dir: data/train
    metadata: data/train_split.csv
    loader:
      batch_size: ${data.default_loader.batch_size}
      num_workers: ${data.default_loader.num_workers}
      load_dicom: ${data.default_loader.load_dicom}
    crop:
      width: 800
      height: 800
    augment: true
  validation:
    data_dir: ${data.train.data_dir}
    metadata: data/validation.csv
    loader:
      batch_size: ${data.default_loader.batch_size}
      num_workers: ${data.default_loader.num_workers}
      load_dicom: ${data.default_loader.load_dicom}
  predict:
    data_dir: data/test
    loader:
      batch_size: ${data.default_loader.batch_size}
      num_workers: ${data.default_loader.num_workers}
      load_dicom: ${data.default_loader.load_dicom}
  default_loader:
    batch_size: 32
    num_workers: 48
    load_dicom: true

model:
  backbone: resnet50
  trainable_backbone_layers: 3
  num_classes: 15

submission:
  file: submission.csv

evaluation:
  iou_threshold: 0.4
  confidence_threshold: 0.2
